apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt  
    server: https://kubernetes.default.svc  
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: jenkins-sa
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins-sa
  user:
    token: 
